services:
  goproxy:
    image: ghcr.io/goproxy/goproxy
    command: "-address=0.0.0.0:8080 -cacher-dir=/go -cacher-max-cache-bytes=32212254720 -go-bin-max-workers=30"
    environment:
      GOPROXY: "https://proxy.golang.org,https://goproxy.io,direct"
      GOMAXPROCS: 1
    ports:
      - 127.0.0.1:8081:8080
    volumes:
      - goproxy-storage:/go
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 3

volumes:
  goproxy-storage:
    external: true
